base:
  name: phanes
  env: dev
  http_listen: :7771
  version: 0.1.0

db:
#  - addr: host=127.0.0.1 user=root password=root dbname=phanes port=5432
#      sslmode=disable TimeZone=Asia/Shanghai
#    pwd: root
#    type: postgres
#    user: root
  - addr: 127.0.0.1:6379
    pwd: ""
    type: redis
    user: ""

broker:
  addr: amqp://coco:kk123123123@127.0.0.1:5672/
  pwd: ""
  type: rabbitmq
  user: ""

# otel config
collect:
  log:
    # log file name
    file_name: admin
    # log print prefix
    prefix: 【Phanes】
  metric:
    addr: ""
  trace:
    addr: ""

traefik:
  enable_router: false
  # reverse proxy type support: tcp udp http grpc(h2c)
  type: tcp
  # support "||" or "&&"
  rule: "&&"
  # is enable tls
  tls: true
  domain: test.com
  # is enable traefik reverse proxy
  enabled: true
  # match prefix
  prefix:
